name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js 23.5.0
        uses: actions/setup-node@v3
        with:
          node-version: 23.5.0

      - name: Install dependencies
        run: npm ci

      # --- Prettier ---
      - name: Check code formatting with Prettier
        run: npx prettier --check '**/*.{ts,tsx,js,jsx,json,css,md}'

      # --- TypeScript type check ---
      - name: Type check
        run: npx tsc --noEmit

